# Generated by Django 5.2.6 on 2026-04-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confetti', '0002_settingssnapshot_alter_settingdefinition_choices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingcategory',
            options={'verbose_name': 'Категория настройки', 'verbose_name_plural': 'Категории настроек'},
        ),
        migrations.AlterModelOptions(
            name='settingdefinition',
            options={'ordering': ['key'], 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='settingvalue',
            options={'verbose_name': 'Значение настройки', 'verbose_name_plural': 'Значения настроек'},
        ),
    ]
